# Generated by Django 3.2.4 on 2021-06-20 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de parroquia')),
                ('tipo', models.CharField(choices=[('urbana', 'urbana'), ('rural', 'rural')], max_length=6, verbose_name='Tipo de parroquia')),
            ],
            options={
                'verbose_name_plural': 'Las Parroquias',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de barrio')),
                ('numViviendas', models.IntegerField(verbose_name='Numero de viviendas')),
                ('numParques', models.IntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco'), (6, 'Sexto')], verbose_name='Numero de parques')),
                ('numEdificios', models.IntegerField(verbose_name='Numero de edificios')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasparroquias', to='ordenamiento.parroquia')),
            ],
            options={
                'verbose_name_plural': 'Los Barrios',
                'ordering': ['nombre'],
            },
        ),
    ]
